fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    alternatives: "git://github.com/puppet-community/puppet-alternatives"
    hadoop_lib: "git://github.com/valtri/cesnet-hadoop_lib"
  symlinks:
    hue: "#{source_dir}"
